/* ================================================================
   DAT 153 -- Data Types & Aggregating with GROUP BY
   Exercises from lessons/lesson_sql_queries_02/_lesson.qmd
   Database: northwind
   ================================================================ */


/* ----------------------------------------------------------------
   Part 1 -- Exercise 1.1

   Every row in order_details records a unit_price and a quantity.
   Write a query that returns order_id, product_id, and the line
   total (unit_price * quantity), explicitly cast to NUMERIC(10,2)
   using CAST(). Limit your results to 10 rows.
   ---------------------------------------------------------------- */



/* ----------------------------------------------------------------
   Part 1 -- Exercise 1.2

   Rewrite Exercise 1.1's cast using the :: operator instead of
   CAST(). Confirm the results are identical.
   ---------------------------------------------------------------- */



/* ----------------------------------------------------------------
   Part 1 -- Exercise 1.3

   Every order in orders has an order_date. Write a query that
   extracts just the year from order_date (look up the EXTRACT
   function) and counts how many orders were placed in each year.
   Sort by year.
   ---------------------------------------------------------------- */



/* ----------------------------------------------------------------
   Part 2 -- Exercise 2.1

   Group products by category_id and count how many products
   belong to each category. Sort the results in descending order
   by count.
   ---------------------------------------------------------------- */



/* ----------------------------------------------------------------
   Part 2 -- Exercise 2.2

   Using the same query as Exercise 2.1, add a HAVING clause so
   that only categories with more than 10 products appear in the
   results.
   ---------------------------------------------------------------- */



/* ----------------------------------------------------------------
   Part 2 -- Exercise 2.3

   Group order_details by product_id to calculate the total
   revenue generated by each product. Revenue for a single line is
   unit_price * quantity * (1 - discount). Round your final revenue
   figure to 2 decimal places, and sort descending by revenue.
   Limit your results to the top 10 products.
   ---------------------------------------------------------------- */



/* ----------------------------------------------------------------
   Part 2 -- Exercise 2.4

   Group orders by ship_country and count how many orders shipped
   to each country. Add a HAVING clause so only countries with more
   than 60 orders appear. Sort descending by count.
   ---------------------------------------------------------------- */



/* ----------------------------------------------------------------
   Part 2 -- Exercise 2.5

   Group orders by employee_id and, for each employee, count the
   number of distinct customers they have taken orders from (hint:
   COUNT(DISTINCT ...)). Return employee_id and that count, sorted
   descending by count.
   ---------------------------------------------------------------- */



/* ----------------------------------------------------------------
   Part 2 -- Exercise 2.6

   Group orders by ship_country and calculate the average freight
   cost per country, rounded to 2 decimal places. Only include
   countries with more than 5 orders. Sort descending by average
   freight.
   ---------------------------------------------------------------- */



/* ----------------------------------------------------------------
   Part 3 -- Exercise 3.1

   Using orders, count how many orders shipped to each city within
   'USA', 'Canada', and 'Mexico' (filter with WHERE ship_country IN
   (...)), but use GROUP BY ROLLUP(ship_country, ship_city) instead
   of a plain GROUP BY. This adds a subtotal row for each country
   (where ship_city is NULL) and one grand-total row (where both
   columns are NULL). Sort by ship_country, then ship_city, placing
   NULL values last.
   ---------------------------------------------------------------- */



/* ----------------------------------------------------------------
   Part 3 -- Exercise 3.2

   Rewrite Exercise 3.1 using GROUP BY CUBE(ship_country, ship_city)
   instead of ROLLUP. Compare the two result sets: CUBE returns more
   rows than ROLLUP for the exact same data. In a comment, explain
   what those extra rows represent, and why ROLLUP doesn't produce
   them.
   ---------------------------------------------------------------- */
